import { AppealRule } from './types';

export const appealRules: AppealRule[] = [
  { drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'uhc', appeals: [
    { denialReason: 'IgE outside 30-1500 range', strategy: 'If IgE >1500: cite ERS/ATS 2020 guidelines supporting omalizumab in severe allergic asthma regardless of IgE level when documented atopy is present. Reference Busse et al. (2001) and Humbert et al. (2005) landmark trials.', citations: ['ERS/ATS 2020 Guidelines', 'Busse et al. JACI 2001', 'Humbert et al. JACI 2005'], letterTemplate: 'appeal-xolair-ige' },
    { denialReason: 'No documented ICS+LABA trial', strategy: 'Pull pharmacy fill records showing ICS+LABA dispensing history. If fill records show >=3 months of high-dose ICS+LABA, submit with prescription dates and pharmacy confirmation. If patient has LABA contraindication, document medical rationale.', citations: ['GINA 2024 Step 5', 'Pharmacy fill records as adherence documentation'], letterTemplate: 'appeal-xolair-step' },
    { denialReason: 'FEV1 >= 80% (not severe)', strategy: 'Cite GINA 2024: spirometry may be normal between exacerbations. Submit ACT score <19 (uncontrolled), exacerbation count >=2/year, OCS bursts, ER visits, and hospitalizations as alternative severity evidence.', citations: ['GINA 2024 Global Strategy', 'Normal spirometry between exacerbations - GINA 2024'], letterTemplate: 'appeal-xolair-fev1' },
    { denialReason: 'No allergen test', strategy: 'Order skin prick test or specific IgE to dust mite, cat, dog, cockroach, mold. Submit results showing perennial aeroallergen reactivity. If test cannot be obtained, document clinical history of allergic triggers.', citations: ['AAAAI Allergen Testing Guidelines'], letterTemplate: 'appeal-xolair-allergen' },
    { denialReason: 'Weight outside 30-150 kg range', strategy: 'Cite FDA dosing information. For weight >150 kg, reference GINA 2024 weight-based dosing considerations. Document clinical need and discuss risk-benefit with prescriber.', citations: ['FDA Xolair Prescribing Information', 'GINA 2024'], letterTemplate: 'appeal-xolair-weight' },
  ]},
  { drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'co-medicaid', appeals: [
    { denialReason: 'Wrong ICD-10 code submitted', strategy: 'Correct to J45.40 (moderate persistent) or J45.50 (severe persistent). Submit corrected PA with proper code. Reference CO Medicaid Appendix Y requirements.', citations: ['CO Medicaid Appendix Y', 'ICD-10-CM Official Guidelines'], letterTemplate: 'appeal-co-medicaid-icd10' },
    { denialReason: 'Required diagnosis not met', strategy: 'Verify ICD-10 code matches Appendix Y. Ensure J45.40 or J45.50 used (not J45.20, J45.30, or J45.901). File reconsideration within 10-day window. Request P2P through Kepro within 5 business days.', citations: ['CO Medicaid Atrezzo Portal', 'Kepro/Acentra Health Review Process'], letterTemplate: 'appeal-co-medicaid-diagnosis' },
  ]},
  { drugId: 'xolair', indicationId: 'csu', payerId: 'uhc', appeals: [
    { denialReason: 'No up-titrated H1 antihistamine trial', strategy: 'Document specific doses: cetirizine 10mg to 20mg to 40mg, or loratadine 10mg to 20mg to 40mg, or fexofenadine 180mg to 360mg. Submit pharmacy fill records showing dose escalation over documented period. Cite AAAAI/ACAAI 2014 Urticaria Practice Parameter.', citations: ['AAAAI/ACAAI 2014 Urticaria Practice Parameter', 'EAACI/GA2LEN Guidelines'], letterTemplate: 'appeal-xolair-csu-step' },
    { denialReason: 'Duration less than 6 weeks', strategy: 'Document chronic urticaria >6 weeks with no identifiable trigger. Submit progress notes, pharmacy records, and patient symptom diary. If intermittent, document pattern of recurrence.', citations: ['AAAAI/ACAAI 2014'], letterTemplate: 'appeal-xolair-csu-duration' },
  ]},
  { drugId: 'xolair', indicationId: 'csu', payerId: 'cigna', appeals: [
    { denialReason: 'Preferred alternative (Dupixent) required', strategy: 'Xolair was FDA-approved for CSU BEFORE Dupixent. Cite ASTERIA I and ASTERIA II trials establishing Xolair efficacy in CSU. If patient has concomitant allergic asthma, Xolair treats both conditions with a single agent.', citations: ['ASTERIA I Trial (Maurer et al. NEJM 2013)', 'ASTERIA II Trial', 'FDA Approval Timeline'], letterTemplate: 'appeal-xolair-csu-preferred' },
  ]},
  { drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'uhc', appeals: [
    { denialReason: 'Eosinophils below 150 threshold', strategy: 'Check if patient is on oral corticosteroids (suppresses eosinophils by >50%). Request pre-OCS historical eosinophil count. Submit FeNO level (>=25 ppb) as alternative biomarker. Cite Wenzel et al. Lancet 2016 showing Dupixent efficacy with FeNO as alternative.', citations: ['Wenzel et al. Lancet 2016', 'Ortega et al. NEJM 2016', 'GINA 2024 Biomarker Guidelines'], letterTemplate: 'appeal-dupixent-eos' },
    { denialReason: 'Another biologic (Xolair) not tried first', strategy: 'If patient has purely eosinophilic phenotype (negative allergen testing, IgE <30), Xolair is NOT appropriate. Cite GINA 2024 Step 5 phenotype-based biologic selection: anti-IL-5/IL-5R/IL-4R agents for T2-high eosinophilic phenotype, anti-IgE only for allergic phenotype.', citations: ['GINA 2024 Step 5', 'Phenotype-Based Biologic Selection'], letterTemplate: 'appeal-dupixent-prior-biologic' },
    { denialReason: 'ICS+LABA trial not documented', strategy: 'Pull pharmacy fill records showing ICS+LABA dispensing with dates. Submit electronic pharmacy records, EHR prescription history, and coordinator attestation of adherence.', citations: ['GINA 2024 Step 4-5', 'Pharmacy Records as Documentation'], letterTemplate: 'appeal-dupixent-step' },
  ]},
  { drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'aetna', appeals: [
    { denialReason: 'Prescriber not a specialist', strategy: 'Have allergist/immunologist or pulmonologist co-sign the PA or provide supporting letter. Document specialist involvement in patient care through referral documentation, consultation notes, or shared care agreement.', citations: ['Aetna Prescriber Policy', 'GINA 2024 Specialist Recommendation'], letterTemplate: 'appeal-dupixent-specialist' },
  ]},
  { drugId: 'dupixent', indicationId: 'atopic-dermatitis', payerId: 'uhc', appeals: [
    { denialReason: 'Topical therapy trial not documented', strategy: 'List each topical agent tried with: drug name, potency class (I-VII), body area treated, duration of use, patient response. Submit pharmacy fill records as supporting evidence. Document any adverse reactions to topicals.', citations: ['AAD 2023 Atopic Dermatitis Guidelines', 'Topical Corticosteroid Potency Classification'], letterTemplate: 'appeal-dupixent-ad-topical' },
    { denialReason: 'Phototherapy not tried', strategy: 'Document barriers to phototherapy: geographic distance from treatment center, work schedule constraints, skin type (Fitzpatrick IV-VI), insurance coverage limitations, patient preference. Cite AAD 2023 guidelines supporting systemic therapy when phototherapy barriers exist.', citations: ['AAD 2023 Guidelines', 'Phototherapy Access Barriers'], letterTemplate: 'appeal-dupixent-ad-phototherapy' },
    { denialReason: 'JAK inhibitor preferred', strategy: 'Document black box warnings for JAK inhibitors (thrombosis, malignancy, cardiovascular events, serious infections). Cite Dupixent favorable long-term safety profile from LIBERTY trials. Highlight pregnancy considerations if applicable.', citations: ['FDA JAK Inhibitor Safety Warnings', 'Simpson et al. NEJM 2020 (LIBERTY AD)', 'Dupixent Safety Profile'], letterTemplate: 'appeal-dupixent-ad-jak' },
  ]},
  { drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'uhc', appeals: [
    { denialReason: 'Eosinophils below 150 threshold', strategy: 'Check OCS use (suppresses eosinophils by >50%). Request pre-OCS historical eosinophil count. UHC accepts >=300 historical within 12 months. Cite Ortega et al. NEJM 2014: benefit demonstrated across eosinophil range >=150.', citations: ['Ortega et al. NEJM 2014', 'Pavord et al. Lancet 2012'], letterTemplate: 'appeal-nucala-eos' },
    { denialReason: 'Exacerbation history insufficient', strategy: 'Compile ALL exacerbation evidence: ER visits, hospitalizations, OCS bursts (>=3 day courses), unscheduled office visits, urgent care visits. Document total exacerbation burden, not just what appears in progress notes.', citations: ['GINA 2024 Exacerbation Definition', 'Pavord et al. Lancet 2012'], letterTemplate: 'appeal-nucala-exacerbation' },
    { denialReason: 'Xolair not tried first', strategy: 'If purely eosinophilic phenotype (IgE <30, negative allergen skin test), document that Xolair requires IgE 30-1500 AND positive allergen test. Patient biomarkers rule out Xolair. Cite GINA 2024 phenotype-based biologic selection.', citations: ['GINA 2024 Step 5', 'Xolair Prescribing Information (IgE 30-1500 requirement)'], letterTemplate: 'appeal-nucala-xolair' },
  ]},
  { drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'co-medicaid', appeals: [
    { denialReason: 'Eosinophils drawn on OCS (suppressed)', strategy: 'Submit pre-OCS historical eosinophil count. Request P2P through Kepro within 5 business days to explain biomarker suppression. Cite that OCS suppresses eosinophils by >50%.', citations: ['Kepro P2P Process', 'Biomarker Suppression Literature', 'Ortega et al. NEJM 2014'], letterTemplate: 'appeal-nucala-co-ocs' },
  ]},
  { drugId: 'fasenra', indicationId: 'eosinophilic-asthma', payerId: 'uhc', appeals: [
    { denialReason: 'Eosinophils below 150 threshold', strategy: 'Same as Nucala. Check OCS suppression, submit pre-OCS historical count.', citations: ['Bleecker et al. Lancet 2016', 'GINA 2024'], letterTemplate: 'appeal-fasenra-eos' },
    { denialReason: 'Preferred alternative (Nucala) not tried', strategy: 'If Nucala already failed: document inadequate response on Nucala (persistent exacerbations, unable to taper OCS). Cite Fasenra unique ADCC mechanism providing more complete eosinophil depletion. Cite Bleecker et al. Lancet 2016. Also document Q8W dosing preference (fewer injections than Nucala Q4W).', citations: ['Bleecker et al. Lancet 2016', 'ADCC Mechanism - Unique eosinophil depletion', 'Q8W dosing convenience'], letterTemplate: 'appeal-fasenra-nucala' },
  ]},
  { drugId: 'tezspire', indicationId: 'severe-asthma', payerId: 'uhc', appeals: [
    { denialReason: 'Another biologic not tried first', strategy: 'Document that patient biomarkers rule out ALL phenotype-specific biologics: eosinophils <150 (rules out Nucala, Fasenra, Cinqair), IgE <30 (rules out Xolair), FeNO <25 (rules out Dupixent), negative allergen testing (rules out Xolair). Tezspire is the ONLY FDA-approved biologic for this patient. Cite NAVIGATOR trial (Menzies-Gow et al. NEJM 2021) showing efficacy across ALL biomarker levels.', citations: ['NAVIGATOR Trial - Menzies-Gow et al. NEJM 2021', 'GINA 2024 Step 5 Phenotype-Based Selection'], letterTemplate: 'appeal-tezspire-prior-biologic' },
    { denialReason: 'Severity not adequately documented', strategy: 'Submit ACT score <19, exacerbation history >=2/year, OCS use, ER/hospitalization records. Document that despite maximum controller therapy (high-dose ICS+LABA+LAMA), asthma remains uncontrolled.', citations: ['GINA 2024 Uncontrolled Asthma Definition', 'ACT Score Interpretation'], letterTemplate: 'appeal-tezspire-severity' },
  ]},
  { drugId: 'tezspire', indicationId: 'severe-asthma', payerId: 'co-medicaid', appeals: [
    { denialReason: 'Medical necessity not met', strategy: 'Comprehensive severity documentation. Submit ACT <19, exacerbation count, OCS use, ER visits, hospitalizations, PFT results. Request P2P through Kepro within 5 business days.', citations: ['CO Medicaid Atrezzo Portal', 'Kepro P2P Process', 'GINA 2024'], letterTemplate: 'appeal-tezspire-co-medical' },
  ]},
  { drugId: 'tezspire', indicationId: 'crswnp-tezspire', payerId: 'aetna', appeals: [
    { denialReason: 'Reauth denied - no clinical response documented', strategy: 'Document response at EACH follow-up visit. Confirm "Patient continues mometasone daily." Include SNOT-22 scores showing improvement. Cite NAVIGATOR-2 trial for Tezspire CRSwNP efficacy.', citations: ['Peter Kane Case (March 9, 2026)', 'NAVIGATOR-2 Trial', 'Aetna Reauth Requirements'], letterTemplate: 'appeal-tezspire-crswnp-reauth' },
    { denialReason: 'No intranasal corticosteroid confirmation', strategy: 'Submit pharmacy records showing ongoing intranasal corticosteroid fills. Document in each progress note: "Patient continues daily mometasone (Nasonex) nasal spray." This is a specific Aetna reauth requirement.', citations: ['Aetna Reauth Criteria', 'Peter Kane Case Precedent'], letterTemplate: 'appeal-tezspire-crswnp-intranasal' },
  ]},
  { drugId: 'cinqair', indicationId: 'eosinophilic-asthma-cinqair', payerId: 'uhc', appeals: [
    { denialReason: 'Eosinophils below 400 threshold', strategy: 'If eosinophils are 150-399: patient qualifies for Nucala or Fasenra (SC, >=150 threshold) but NOT Cinqair. If IV route specifically needed: document inability to self-inject, needle phobia, adherence concerns, or prior SC biologic failure. Cite that Cinqair is IV-only for patients who cannot use SC alternatives.', citations: ['Cinqair Prescribing Information (400 eosinophil threshold)', 'Nucala Prescribing Information (150 threshold)'], letterTemplate: 'appeal-cinqair-eos' },
    { denialReason: 'SC alternative preferred', strategy: 'If BOTH Nucala and Fasenra have failed: document each failure with dates, duration, and reason for discontinuation (inadequate response, adverse events). Only then is Cinqair (IV, different dosing schedule) appropriate.', citations: ['Step Therapy - Sequential Biologic Trials', 'GINA 2024'], letterTemplate: 'appeal-cinqair-sc-alt' },
  ]},
  { drugId: 'exdensur', indicationId: 'eosinophilic-asthma-exdensur', payerId: 'uhc', appeals: [
    { denialReason: 'New drug not on formulary', strategy: 'File formulary exception with: FDA approval letter (December 2025), SWIFT trial results (Khurana et al. NEJM 2023) demonstrating non-inferiority to Nucala/Fasenra, current anti-IL-5 prescription, Q6M dosing advantage (2 injections vs 13 per year), and cost-effectiveness argument.', citations: ['FDA Approval December 2025', 'SWIFT Trial - Khurana et al. NEJM 2023', 'Q6M Dosing Advantage'], letterTemplate: 'appeal-exdensur-formulary' },
    { denialReason: 'Patient not on current anti-IL-5 therapy', strategy: 'Exdensur is NOT for anti-IL-5 naive patients. It is a step-DOWN maintenance therapy. Patient must be currently controlled on Nucala or Fasenra. Start with Nucala or Fasenra first, then consider switch to Exdensur after disease control is established.', citations: ['FDA Exdensur Label (Step-Down Therapy)', 'SWIFT Trial Design'], letterTemplate: 'appeal-exdensur-naive' },
  ]},
];

export function getAppealStrategies(drugId: string, indicationId: string, payerId: string) {
  let rule = appealRules.find(r => r.drugId === drugId && r.indicationId === indicationId && r.payerId === payerId);
  if (!rule) rule = appealRules.find(r => r.drugId === drugId && r.indicationId === indicationId);
  if (!rule) rule = appealRules.find(r => r.drugId === drugId);
  return rule ? rule.appeals : [];
}
