import type { GapCheckRule } from './types';

export const gapCheckRules: GapCheckRule[] = [
  // ==================== XOLAIR - ALLERGIC ASTHMA ====================
  // IgE range
  { id: 'xolair-ige-low', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'IgE must be >= 30 IU/mL', checkFn: 'Compare IgE value to 30', severity: 'critical', threshold: '>= 30 IU/mL', guidance: 'Xolair dosing table requires IgE >= 30. Document baseline IgE level.' },
  { id: 'xolair-ige-high', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'IgE must be <= 1500 IU/mL', checkFn: 'Compare IgE value to 1500', severity: 'critical', threshold: '<= 1500 IU/mL', guidance: 'IgE > 1500 is outside Xolair dosing table. Consider alternative.' },
  { id: 'xolair-ige-low-bcbs', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'bcbs', category: 'Biomarker', rule: 'IgE must be >= 30 IU/mL', checkFn: 'Compare IgE to 30', severity: 'critical', threshold: '>= 30 IU/mL', guidance: 'BCBS requires IgE >= 30 for Xolair.' },
  { id: 'xolair-ige-high-bcbs', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'bcbs', category: 'Biomarker', rule: 'IgE must be <= 1500 IU/mL', checkFn: 'Compare IgE to 1500', severity: 'critical', threshold: '<= 1500 IU/mL', guidance: 'IgE > 1500 is outside dosing range.' },
  { id: 'xolair-ige-cigna', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'cigna', category: 'Biomarker', rule: 'IgE must be 30-1500 IU/mL', checkFn: 'Compare IgE to range', severity: 'critical', threshold: '30-1500 IU/mL', guidance: 'Cigna enforces strict IgE range.' },
  // Weight
  { id: 'xolair-weight-cigna-low', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'cigna', category: 'Patient Criteria', rule: 'Weight must be >= 30 kg', checkFn: 'Compare weight to 30', severity: 'critical', threshold: '>= 30 kg', guidance: 'Cigna specifically requires weight >= 30 kg for Xolair dosing.' },
  { id: 'xolair-weight-cigna-high', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'cigna', category: 'Patient Criteria', rule: 'Weight must be <= 150 kg', checkFn: 'Compare weight to 150', severity: 'warning', threshold: '<= 150 kg', guidance: 'Weight > 150 kg may require dosing table adjustment.' },
  // Step therapy
  { id: 'xolair-step-therapy-uhc', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records for 3+ months', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Pull pharmacy records. Document fill dates and PDC.' },
  { id: 'xolair-step-therapy-bcbs', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'bcbs', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records for 3+ months', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Document step therapy compliance with pharmacy records.' },
  { id: 'xolair-step-therapy-cigna', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'cigna', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required.' },
  { id: 'xolair-step-therapy-aetna', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'aetna', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Aetna step therapy requirement.' },
  { id: 'xolair-step-therapy-medicare', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'medicare', category: 'Step Therapy', rule: 'ICS+LABA documented failure', checkFn: 'Check records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Medicare requires documented failure.' },
  { id: 'xolair-step-therapy-comed', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'Triple therapy (ICS+LABA+LAMA/LTRA) required', checkFn: 'Check for triple therapy', severity: 'critical', threshold: 'Triple therapy 3+ months', guidance: 'CO Medicaid often requires ICS+LABA+LAMA or ICS+LABA+LTRA for 3+ months.' },
  // FEV1
  { id: 'xolair-fev1-comed', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'co-medicaid', category: 'Pulmonary Function', rule: 'FEV1 must be < 80% predicted', checkFn: 'Compare FEV1 to 80%', severity: 'warning', threshold: '< 80% predicted', guidance: 'CO Medicaid may require FEV1 < 80% for biologic authorization.' },
  // ACT
  { id: 'xolair-act-comed', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'co-medicaid', category: 'Asthma Control', rule: 'ACT score must be < 19 (uncontrolled)', checkFn: 'Compare ACT to 19', severity: 'warning', threshold: '< 19 (uncontrolled)', guidance: 'CO Medicaid requires ACT documentation. Score < 19 = uncontrolled.' },
  // Specialist
  { id: 'xolair-specialist-aetna', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'aetna', category: 'Prescriber', rule: 'Must be prescribed by allergist or pulmonologist', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist prescriber. If PCP, obtain specialist co-sign or referral.' },
  // Allergic phenotype
  { id: 'xolair-allergic-phenotype', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Positive skin test or specific IgE required', checkFn: 'Check for allergic sensitization documentation', severity: 'critical', threshold: 'Positive SPT or sIgE', guidance: 'Must document allergic sensitization to perennial allergen.' },
  { id: 'xolair-allergic-phenotype-bcbs', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'bcbs', category: 'Biomarker', rule: 'Positive skin test or specific IgE required', checkFn: 'Check for allergic sensitization', severity: 'critical', threshold: 'Positive SPT or sIgE', guidance: 'Confirms allergic phenotype for Xolair.' },
  // ICD-10
  { id: 'xolair-icd10-severity', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'uhc', category: 'ICD-10 Coding', rule: 'ICD-10 must specify moderate or severe persistent', checkFn: 'Check ICD-10 code specificity', severity: 'critical', threshold: 'J45.40, J45.50, J45.41, or J45.51', guidance: 'UHC rejects unspecified codes (J45.909). Use J45.40-J45.51.' },
  { id: 'xolair-icd10-severity-comed', drugId: 'xolair', indicationId: 'allergic-asthma', payerId: 'co-medicaid', category: 'ICD-10 Coding', rule: 'ICD-10 must specify SEVERE persistent only', checkFn: 'Check ICD-10 code', severity: 'critical', threshold: 'J45.50 or J45.51 only', guidance: 'CO Medicaid ONLY accepts severe persistent (J45.50/J45.51). J45.40 will be rejected.' },

  // ==================== XOLAIR - CSU ====================
  { id: 'xolair-csu-antihistamine', drugId: 'xolair', indicationId: 'csu', payerId: 'uhc', category: 'Step Therapy', rule: 'H1-antihistamine trial (2+ drugs, 6+ weeks) required', checkFn: 'Check antihistamine prescription history', severity: 'critical', threshold: '2+ H1-antihistamines, 6+ weeks each', guidance: 'Document trial of at least 2 H1-antihistamines from different classes for 6+ weeks.' },
  { id: 'xolair-csu-antihistamine-bcbs', drugId: 'xolair', indicationId: 'csu', payerId: 'bcbs', category: 'Step Therapy', rule: 'H1-antihistamine trial (2+ drugs, 6+ weeks) required', checkFn: 'Check antihistamine history', severity: 'critical', threshold: '2+ H1-antihistamines, 6+ weeks', guidance: 'Required step therapy.' },
  { id: 'xolair-csu-antihistamine-comed', drugId: 'xolair', indicationId: 'csu', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'H1-antihistamine + H2-blocker trial required', checkFn: 'Check both H1 and H2 blocker trials', severity: 'critical', threshold: 'H1 + H2 blocker, 6+ weeks', guidance: 'CO Medicaid may require H2-blocker trial in addition to H1-antihistamines.' },
  { id: 'xolair-csu-uas7', drugId: 'xolair', indicationId: 'csu', payerId: 'uhc', category: 'Clinical Assessment', rule: 'UAS7 score required to document activity', checkFn: 'Check for UAS7 documentation', severity: 'warning', threshold: 'UAS7 >= 16 (active disease)', guidance: 'Document UAS7 score to show active disease despite treatment.' },

  // ==================== DUPIXENT - EOSINOPHILIC ASTHMA ====================
  { id: 'dupixent-eos-uhc', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Eosinophils must be >= 150 cells/mcL', checkFn: 'Compare eosinophil count to 150', severity: 'critical', threshold: '>= 150 cells/mcL', guidance: 'Dupixent eosinophilic asthma requires eos >= 150.' },
  { id: 'dupixent-eos-bcbs', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'bcbs', category: 'Biomarker', rule: 'Eosinophils must be >= 150 cells/mcL', checkFn: 'Compare eos to 150', severity: 'critical', threshold: '>= 150 cells/mcL', guidance: 'Required for eosinophilic phenotype.' },
  { id: 'dupixent-eos-suppressed', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Check if eosinophils suppressed by OCS (>50% suppression)', checkFn: 'If patient on OCS, check pre-OCS eos count', severity: 'warning', threshold: 'OCS can suppress eos >50%', guidance: 'If patient is on OCS, OCS suppresses eosinophils >50%. Submit pre-OCS eosinophil count.' },
  { id: 'dupixent-step-uhc', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Document ICS+LABA fill history.' },
  { id: 'dupixent-step-bcbs', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'bcbs', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required step therapy.' },
  { id: 'dupixent-step-comed', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'Triple therapy (ICS+LABA+LAMA/LTRA) required', checkFn: 'Check for triple therapy', severity: 'critical', threshold: 'Triple therapy 3+ months', guidance: 'CO Medicaid often requires triple therapy.' },
  { id: 'dupixent-fev1-comed', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'co-medicaid', category: 'Pulmonary Function', rule: 'FEV1 should be < 80% predicted', checkFn: 'Compare FEV1 to 80%', severity: 'warning', threshold: '< 80% predicted', guidance: 'CO Medicaid may require FEV1 < 80%.' },
  { id: 'dupixent-specialist-aetna', drugId: 'dupixent', indicationId: 'eosinophilic-asthma', payerId: 'aetna', category: 'Prescriber', rule: 'Specialist prescriber required', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist prescriber.' },

  // ==================== DUPIXENT - ATOPIC DERMATITIS ====================
  { id: 'dupixent-ad-topical', drugId: 'dupixent', indicationId: 'atopic-dermatitis', payerId: 'uhc', category: 'Step Therapy', rule: 'Topical corticosteroid trial required', checkFn: 'Check for topical steroid prescription', severity: 'critical', threshold: 'Topical corticosteroid trial', guidance: 'Document trial and failure of topical corticosteroids.' },
  { id: 'dupixent-ad-easi', drugId: 'dupixent', indicationId: 'atopic-dermatitis', payerId: 'uhc', category: 'Clinical Assessment', rule: 'EASI score >= 16 (moderate-to-severe) required', checkFn: 'Check EASI score', severity: 'critical', threshold: 'EASI >= 16', guidance: 'Document EASI score to confirm moderate-to-severe disease.' },
  { id: 'dupixent-ad-iga', drugId: 'dupixent', indicationId: 'atopic-dermatitis', payerId: 'uhc', category: 'Clinical Assessment', rule: 'IGA score 3 or 4 required', checkFn: 'Check IGA score', severity: 'warning', threshold: 'IGA 3 or 4', guidance: 'Document IGA score for severity confirmation.' },
  { id: 'dupixent-ad-calcineurin-cigna', drugId: 'dupixent', indicationId: 'atopic-dermatitis', payerId: 'cigna', category: 'Step Therapy', rule: 'Calcineurin inhibitor trial required', checkFn: 'Check for tacrolimus/pimecrolimus trial', severity: 'critical', threshold: 'Calcineurin inhibitor trial', guidance: 'Cigna requires documented calcineurin inhibitor trial.' },
  { id: 'dupixent-ad-calcineurin-comed', drugId: 'dupixent', indicationId: 'atopic-dermatitis', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'Calcineurin inhibitor trial required', checkFn: 'Check for tacrolimus/pimecrolimus trial', severity: 'critical', threshold: 'Calcineurin inhibitor trial', guidance: 'CO Medicaid requires this.' },

  // ==================== NUCALA - EOSINOPHILIC ASTHMA ====================
  { id: 'nucala-eos-uhc', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Eosinophils must be >= 150 cells/mcL', checkFn: 'Compare eos to 150', severity: 'critical', threshold: '>= 150 cells/mcL', guidance: 'Nucala requires eos >= 150.' },
  { id: 'nucala-eos-bcbs', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'bcbs', category: 'Biomarker', rule: 'Eosinophils must be >= 150 cells/mcL', checkFn: 'Compare eos to 150', severity: 'critical', threshold: '>= 150 cells/mcL', guidance: 'Required.' },
  { id: 'nucala-eos-suppressed', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Check OCS suppression of eosinophils', checkFn: 'If on OCS, check pre-OCS eos count', severity: 'warning', threshold: 'OCS suppresses eos >50%', guidance: 'Submit pre-OCS eosinophil count if available.' },
  { id: 'nucala-step-uhc', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required step therapy.' },
  { id: 'nucala-step-comed', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'Triple therapy required', checkFn: 'Check for triple therapy', severity: 'critical', threshold: 'Triple therapy 3+ months', guidance: 'CO Medicaid often requires triple therapy.' },
  { id: 'nucala-specialist-aetna', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'aetna', category: 'Prescriber', rule: 'Specialist prescriber required', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist.' },
  { id: 'nucala-act-comed', drugId: 'nucala', indicationId: 'eosinophilic-asthma', payerId: 'co-medicaid', category: 'Asthma Control', rule: 'ACT score must be < 19', checkFn: 'Compare ACT to 19', severity: 'warning', threshold: '< 19 (uncontrolled)', guidance: 'CO Medicaid requires ACT documentation.' },

  // ==================== FASENRA - EOSINOPHILIC ASTHMA ====================
  { id: 'fasenra-eos-uhc', drugId: 'fasenra', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Eosinophils must be >= 150 cells/mcL', checkFn: 'Compare eos to 150', severity: 'critical', threshold: '>= 150 cells/mcL', guidance: 'Fasenra requires eos >= 150.' },
  { id: 'fasenra-eos-suppressed', drugId: 'fasenra', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Biomarker', rule: 'Check OCS suppression of eosinophils', checkFn: 'If on OCS, check pre-OCS eos count', severity: 'warning', threshold: 'OCS suppresses eos >50%', guidance: 'Submit pre-OCS eosinophil count if available.' },
  { id: 'fasenra-step-uhc', drugId: 'fasenra', indicationId: 'eosinophilic-asthma', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required.' },
  { id: 'fasenra-specialist-aetna', drugId: 'fasenra', indicationId: 'eosinophilic-asthma', payerId: 'aetna', category: 'Prescriber', rule: 'Specialist prescriber required', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist.' },

  // ==================== TEZSPIRE - SEVERE ASTHMA ====================
  { id: 'tezspire-step-uhc', drugId: 'tezspire', indicationId: 'severe-asthma', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required step therapy.' },
  { id: 'tezspire-step-comed', drugId: 'tezspire', indicationId: 'severe-asthma', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'Triple therapy (ICS+LABA+LAMA/LTRA) required', checkFn: 'Check for triple therapy', severity: 'critical', threshold: 'Triple therapy 3+ months', guidance: 'CO Medicaid often requires triple therapy.' },
  { id: 'tezspire-specialist-aetna', drugId: 'tezspire', indicationId: 'severe-asthma', payerId: 'aetna', category: 'Prescriber', rule: 'Specialist prescriber required', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist.' },
  { id: 'tezspire-act-comed', drugId: 'tezspire', indicationId: 'severe-asthma', payerId: 'co-medicaid', category: 'Asthma Control', rule: 'ACT score must be < 19', checkFn: 'Compare ACT to 19', severity: 'warning', threshold: '< 19 (uncontrolled)', guidance: 'CO Medicaid requires ACT documentation.' },

  // ==================== CINQAIR - EOSINOPHILIC ASTHMA ====================
  { id: 'cinqair-eos-uhc', drugId: 'cinqair', indicationId: 'eosinophilic-asthma-cinqair', payerId: 'uhc', category: 'Biomarker', rule: 'Eosinophils must be >= 400 cells/mcL (UNIQUE)', checkFn: 'Compare eos to 400', severity: 'critical', threshold: '>= 400 cells/mcL', guidance: 'Cinqair has HIGHER eos threshold than Nucala/Fasenra (400 vs 150).' },
  { id: 'cinqair-eos-bcbs', drugId: 'cinqair', indicationId: 'eosinophilic-asthma-cinqair', payerId: 'bcbs', category: 'Biomarker', rule: 'Eosinophils must be >= 400 cells/mcL', checkFn: 'Compare eos to 400', severity: 'critical', threshold: '>= 400 cells/mcL', guidance: 'Cinqair requires >= 400.' },
  { id: 'cinqair-eos-suppressed', drugId: 'cinqair', indicationId: 'eosinophilic-asthma-cinqair', payerId: 'uhc', category: 'Biomarker', rule: 'Check OCS suppression of eosinophils', checkFn: 'If on OCS, check pre-OCS eos count', severity: 'warning', threshold: 'OCS suppresses eos >50%', guidance: 'CRITICAL: OCS suppresses eos >50%. Submit pre-OCS count. This is especially important for Cinqair 400 threshold.' },
  { id: 'cinqair-step-uhc', drugId: 'cinqair', indicationId: 'eosinophilic-asthma-cinqair', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required.' },
  { id: 'cinqair-specialist-aetna', drugId: 'cinqair', indicationId: 'eosinophilic-asthma-cinqair', payerId: 'aetna', category: 'Prescriber', rule: 'Specialist prescriber required', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist.' },

  // ==================== EXDENSUR - EOSINOPHILIC ASTHMA ====================
  { id: 'exdensur-eos-uhc', drugId: 'exdensur', indicationId: 'eosinophilic-asthma-exdensur', payerId: 'uhc', category: 'Biomarker', rule: 'Eosinophils must be >= 150 cells/mcL', checkFn: 'Compare eos to 150', severity: 'critical', threshold: '>= 150 cells/mcL', guidance: 'Exdensur requires eos >= 150.' },
  { id: 'exdensur-step-uhc', drugId: 'exdensur', indicationId: 'eosinophilic-asthma-exdensur', payerId: 'uhc', category: 'Step Therapy', rule: 'ICS+LABA for 3+ months required', checkFn: 'Check pharmacy records', severity: 'critical', threshold: '3 months ICS+LABA', guidance: 'Required step therapy.' },
  { id: 'exdensur-specialist-aetna', drugId: 'exdensur', indicationId: 'eosinophilic-asthma-exdensur', payerId: 'aetna', category: 'Prescriber', rule: 'Specialist prescriber required', checkFn: 'Check prescriber specialty', severity: 'critical', threshold: 'Allergist or Pulmonologist', guidance: 'Aetna requires specialist.' },

  // ==================== XOLAIR - CRSwNP ====================
  { id: 'xolair-crswnp-surgery-uhc', drugId: 'xolair', indicationId: 'crswnp', payerId: 'uhc', category: 'Step Therapy', rule: 'Failed prior sinus surgery required', checkFn: 'Check for FESS/polypectomy records', severity: 'critical', threshold: 'Prior FESS or polypectomy', guidance: 'Most payers require documented failure of prior sinus surgery.' },
  { id: 'xolair-crswnp-topical-uhc', drugId: 'xolair', indicationId: 'crswnp', payerId: 'uhc', category: 'Step Therapy', rule: 'Intranasal corticosteroid trial required', checkFn: 'Check for intranasal steroid prescription', severity: 'critical', threshold: 'Intranasal corticosteroid trial', guidance: 'Document trial and failure of intranasal corticosteroids.' },
  { id: 'xolair-crswnp-surgery-comed', drugId: 'xolair', indicationId: 'crswnp', payerId: 'co-medicaid', category: 'Step Therapy', rule: 'Failed prior sinus surgery required', checkFn: 'Check for FESS records', severity: 'critical', threshold: 'Prior FESS', guidance: 'CO Medicaid requires failed surgery.' },

  // ==================== XOLAIR - FOOD ALLERGY ====================
  { id: 'xolair-food-ofc-uhc', drugId: 'xolair', indicationId: 'food-allergy', payerId: 'uhc', category: 'Clinical Assessment', rule: 'Oral Food Challenge results recommended', checkFn: 'Check for OFC documentation', severity: 'warning', threshold: 'Documented OFC reactivity', guidance: 'OFC is gold standard for food allergy diagnosis. Recommended for strong PA.' },
  { id: 'xolair-food-anaphylaxis-uhc', drugId: 'xolair', indicationId: 'food-allergy', payerId: 'uhc', category: 'Clinical Assessment', rule: 'Anaphylaxis history should be documented', checkFn: 'Check for anaphylaxis documentation', severity: 'warning', threshold: 'Documented anaphylaxis episodes', guidance: 'Document any history of anaphylaxis to strengthen PA.' },
];

/**
 * Get all applicable gap check rules for a given drug+indication+payer combination.
 */
export function getApplicableRules(drugId: string, indicationId: string, payerId: string): GapCheckRule[] {
  return gapCheckRules.filter(
    (r) => r.drugId === drugId && r.indicationId === indicationId && r.payerId === payerId
  );
}

/**
 * Get rules by payer across all drugs/indications (for general payer rules)
 */
export function getRulesForPayer(payerId: string): GapCheckRule[] {
  return gapCheckRules.filter((r) => r.payerId === payerId);
}
